### ISSUE TITLE
Possible multithreading issue in iterator function of MapEntrySetStore class

### ISSUE THREAD

**Issue by aihuaxu** [datanucleus/datanucleus-rdbms#183] opened 2017-03-17 20:19 UTC
## Bug Report: Race condition could occur inside MapEntrySetStore:iterator()

Here is a scenario which will run into NullPonterException:

* 2 threads are holding the same MapEntrySetStore object and both find iteratorStmtLocked is null and reach line 351.
* Thread 1 sets the iteratorMappingParams and exits the sync block to line 361.
* Thread 2 actually will reenter sync block and reset iteratorMappingParams. There is a moment iteratorMappingParams is empty (right after line 520).
Thread 1 at that moment continues execution and reaches 372, then it will throws NPE.

Here is the code which will cause the issue. Basically iteratorMappingParams can be read and initialized at the same time.

```
    public Iterator<Map.Entry<K, V>> iterator(ObjectProvider ownerOP)
    {
        ExecutionContext ec = ownerOP.getExecutionContext();
        if (iteratorStmtLocked == null)
        {
351            synchronized (this) // Make sure this completes in case another thread needs the same info
            {
                // Generate the statement, and statement mapping/parameter information
                SQLStatement sqlStmt = getSQLStatementForIterator(ownerOP);
                iteratorStmtUnlocked = sqlStmt.getSQLText().toSQL();
                sqlStmt.addExtension(SQLStatement.EXTENSION_LOCK_FOR_UPDATE, true);
                iteratorStmtLocked = sqlStmt.getSQLText().toSQL();
            }
        }

361        Transaction tx = ec.getTransaction();
        String stmt = (tx.getSerializeRead() != null && tx.getSerializeRead() ? iteratorStmtLocked : iteratorStmtUnlocked);
        try
        {
            ManagedConnection mconn = storeMgr.getConnection(ec);
            SQLController sqlControl = storeMgr.getSQLController();
            try
            {
                // Create the statement and set the owner
                PreparedStatement ps = sqlControl.getStatementForQuery(mconn, stmt);
372                StatementMappingIndex ownerIdx = iteratorMappingParams.getMappingForParameter("owner");
```

**Comment by aihuaxu** [comment] 2017-03-21 20:32
@andyjefferson Thanks for checking this issue. Unfortunately it's very hard to provide a test case for this since it's a rare race condition.  

Here is the stack trace from Hive+Sentry. Not sure if that will help. This is with older version of DN though.

java.lang.RuntimeException: MetaException(message:java.lang.NullPointerException) 
        at org.apache.sentry.hdfs.MetastoreCacheInitializer.createInitialUpdate(MetastoreCacheInitializer.java:332) 
        at org.apache.sentry.hdfs.MetastorePlugin$1.run(MetastorePlugin.java:161) 
        at org.apache.sentry.hdfs.MetastorePlugin.<init>(MetastorePlugin.java:198) 
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) 
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) 
        at org.apache.sentry.binding.metastore.SentryMetastorePostEventListener.<init>(SentryMetastorePostEventListener.java:78) 
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) 
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) 
        at org.apache.hadoop.hive.metastore.MetaStoreUtils.getMetaStoreListeners(MetaStoreUtils.java:1440) 
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.init(HiveMetaStore.java:528) 
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.<init>(RetryingHMSHandler.java:78) 
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.getProxy(RetryingHMSHandler.java:84) 
        at org.apache.hadoop.hive.metastore.HiveMetaStore.newRetryingHMSHandler(HiveMetaStore.java:5962) 
        at org.apache.hadoop.hive.metastore.HiveMetaStore.newRetryingHMSHandler(HiveMetaStore.java:5957) 
        at org.apache.hadoop.hive.metastore.HiveMetaStore.startMetaStore(HiveMetaStore.java:6209) 
        at org.apache.hadoop.hive.metastore.HiveMetaStore.main(HiveMetaStore.java:6134) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
        at java.lang.reflect.Method.invoke(Method.java:606) 
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221) 
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136) 
Caused by: MetaException(message:java.lang.NullPointerException) 
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.newMetaException(HiveMetaStore.java:5597) 
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_table_objects_by_name(HiveMetaStore.java:1961) 
        at org.apache.sentry.hdfs.MetastoreCacheInitializer$TableTask.doTask(MetastoreCacheInitializer.java:191) 
        at org.apache.sentry.hdfs.MetastoreCacheInitializer$BaseTask$RetryStrategy.exec(MetastoreCacheInitializer.java:94) 
        at org.apache.sentry.hdfs.MetastoreCacheInitializer$BaseTask.call(MetastoreCacheInitializer.java:134) 
        at org.apache.sentry.hdfs.MetastoreCacheInitializer$BaseTask.call(MetastoreCacheInitializer.java:63) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
        at java.lang.Thread.run(Thread.java:745) 
Caused by: java.lang.NullPointerException 
        at org.datanucleus.store.rdbms.scostore.MapEntrySetStore.iterator(MapEntrySetStore.java:395) 
        at org.datanucleus.store.types.SCOUtils.populateMapDelegateWithStoreData(SCOUtils.java:956)
        at org.datanucleus.store.types.backed.Map.loadFromStore(Map.java:308) 
        at org.datanucleus.store.types.backed.Map.entrySet(Map.java:431) 
        at com.google.common.collect.Maps$FilteredEntryMap.<init>(Maps.java:1798) 
        at com.google.common.collect.Maps.filterEntries(Maps.java:1501) 
        at com.google.common.collect.Maps.filterValues(Maps.java:1418) 
        at org.apache.hadoop.hive.metastore.MetaStoreUtils.trimMapNulls(MetaStoreUtils.java:1660) 
        at org.apache.hadoop.hive.metastore.ObjectStore.convertMap(ObjectStore.java:1266) 
        at org.apache.hadoop.hive.metastore.ObjectStore.convertToTable(ObjectStore.java:1285) 
        at org.apache.hadoop.hive.metastore.ObjectStore.getTableObjectsByName(ObjectStore.java:1242) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
        at java.lang.reflect.Method.invoke(Method.java:606) 
        at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:114) 
        at com.sun.proxy.$Proxy10.getTableObjectsByName(Unknown Source) 
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_table_objects_by_name(HiveMetaStore.java:1949)

**Comment by andyjefferson** [comment] 2017-03-28 06:52
If it is "very hard to provide a testcase" then the problem is for you to resolve, since only you see it and only you can judge when it is fixed. Clearly no proposed fix will be applied to old versions so suggest that you use something recent and base your fix on those

**Comment by andyjefferson** [comment] 2017-08-08 08:45
Still no testcase, no way of seeing the problem, and no proposed fix, so closing. 

Kindly provide a pull request if you get around to looking at this, because it is not a problem to me

**Closed by andyjefferson** 2017-08-08 08:45 UTC
Labels: testcase_required, unresourced
