### ISSUE TITLE
Retrieving an object which contains a N-1 relation to a subclass-table object in a fetch group causes an infinite loop with implicit transactions

### ISSUE THREAD

**Issue by benze** [datanucleus/datanucleus-rdbms#369] opened 2021-05-04 20:01 UTC
The following structure causes an infinite StackOverflow loop within the `org.datanucleus.store.rdbms.ConnectionFactoryImpl.ManagedConnectionImpl#release()` method when it attempts to release the connection:

- ObjectA having a relation to Object B
- ObjectB field included in the fetch group for ObjectA
- Object B & Object C both being subclasses of Object D
-- Object D defined as inheritance: `SUBCLASS_TABLE`
-- Object B & C defined as inheritance: `NEW_TABLE`
- implicit transaction used (no explicit `tx.begin()` or `tx.commit()`)

See: https://github.com/benze/test-jdo/tree/implicit-transaction-errors

Expected Behaviour:
- ObjectA is retrieved with ObjectB's FK

Actual Behaviour
- Infinite loop while retrieving ObjectA

**Additional Info:**
I am using an Abstract class with 2 subclass tables as my N-1 relation.  I do see a warning from DN that this is not fully supported so I don't know if that is the root cause, however, oddly enough, it works fine with transaction boundaries explicitly defined.

If, however, I use implicit transactions (and remove the `tx.begin()` and `tx.commit()`), the test fails with an endless loop and generates a StackOverflow issue.  I have traced down the issue into something in the `org.datanucleus.store.rdbms.ConnectionFactoryImpl.ManagedConnectionImpl#release()` as it tries to commitOnRelease, but get a little bit lost in the logic as to why the release is trying to iterate to the end of an open result set instead of just closing the result set as such.

Thanks,

Eric

**Comment by andyjefferson** [comment] 2021-05-05 07:33
Log says 
08:28:28,981 (main) WARN  [DataNucleus.Query] - Relation (mydomain.model.Person.address) with multiple related tables (using subclass-table). Not supported so selecting FK of related object only

which is the source of the problem (not that StackOverflow is an acceptable "result"). You have a relation with no referential integrity ("id" column in Person table, which maps to either the "id" of POBox table or the "id" of House table) and there is no provided way of generating SQL that would pull in the "FK" for that situation, since it doesn't know which of the subclasses that purports to.

**Workaround**, when wanting to run non-transactional, is to set datanucleus.connection.nontx.releaseAfterUse to false. That avoids the StackOverflow since it doesn't try to close the connection, and hence query results. Doesn't provide a way of pulling in a FK in that situation, but then mentioned before that the JDO spec and DataNucleus do not provide a way of just retrieving a FK "value" and doing nothing with it.

**Comment by benze** [comment] 2021-05-05 18:11
> You have a relation with no referential integrity ("id" column in Person table, which maps to either the "id" of POBox table or the "id" of House table) and there is no provided way of generating SQL that would pull in the "FK" for that situation, since it doesn't know which of the subclasses that purports to.

I realize that is partly the genesis of the issue.  I did notice that given that structural issue, that DN will generate a UNION query across all subclass tables to identify which table needs to be queried for the related object.  So while this may not be structurally sound, I do not believe this falls outside JPA/JDO spec (and unfortunately my given data structure).


> The reason for the connection close and subsequent stackoverflow is that this query executes, has the connection marked to close after a single operation, so tries to load results of the query, but this then triggers an attempt to find the related object (though the connection is already in the process of being closed) so it goes into a death spiral. 

I suppose I am confused as to why it is trying to load the complete object at that point and not just the FK.  With the DN extension denoting the field as `fetch-fk-only`, I would have expected that it does not try to find the related object, and retrieve the FK only.  However, in trying to step through the code, I was unable to find where it would ever query the `org.datanucleus.store.rdbms.sql.SQLStatementHelper#selectFetchPlanFieldsOfFKRelatedObject()` method to identify if/how to retrieve the given fields.  I tried to drill through the logic and identifying where that load/check is made with the context of loading the object but came up empty.


> Workaround 1, when wanting to run non-transactional, is to set datanucleus.connection.nontx.releaseAfterUse to false. 
I've read the docs for the setting, but wouldn't that potentially risk the same issue (at a later point in the transaction)?  At some point, the PM will be closed/released, which (I expect) would then make a to `connection.close()`.  At which point, wouldn't this same issue be triggered?  Doesn't this setting just delay the release of the connection to the close of the PM?

**Comment by andyjefferson** [comment] 2021-05-05 18:25
Nobody says lack of relational integrity (RI) is "outside" the spec. It is simply the cause of your problem. Do this and you inconvenience the persistence process (and potentially slow things down, as well as open up the box of lack of RI). Your choice.

As per https://datanucleus.groups.io/g/main/message/351?p=,,,50,0,0,0::created,0,,1,2,0,351 "fetch-fk-only" is there as a shortcut for people who are lazy and don't want to specify their fetch plan each use (it does option 1 in that link, but for the PK field(s) only). It will create an OBJECT for the related field, and LOAD THE PK only. There is no such thing in the JDO spec and in DataNucleus to select the "FK" (which is simply a number in your case, but could be a composite PK just as easily) and do nothing with it, storing it somewhere without instantiating the related object. It is NOT loading the whole object. It is avoiding a JOIN (which cannot be done anyway in your example here). Clearly people could contribute code to fetch a "FK" and store it somewhere for later use if they really wanted that.

No, workaround 1 will not risk anything. Your single user operation is causing 2 SQL invocations, and those 2 are interfering with the connection, so keeping it open gets around that.

**Comment by andyjefferson** [comment] 2021-05-10 08:00
Fixed by associated issue in datanucleus-core. Will be backported to 5.2 at some point

**Closed by andyjefferson** 2021-05-10 08:00 UTC
Labels: bug
