### ISSUE TITLE
[BUG][MYSQL] Column name mismatch when checking for primary key specifications

### ISSUE THREAD

**Issue by Aggarwal-Raghav** [datanucleus/datanucleus-rdbms#496] opened 2024-08-17 16:10 UTC
During Apache Hive datanucleus version upgrade to 6.x (for java 17 compatible), I observed this issue. I have created a sample project for reproducing this issue with datanucleus 6.x and have attached the screenshots for debugging (possible problematic code) and stacktrace.

**Here is the project URL**: https://github.com/Aggarwal-Raghav/DatanucleusIssue496

**The same is working for datanucleus 5.x verison** which is currenly used by Apache Hive. Have tested in branch: [workingCase](https://github.com/Aggarwal-Raghav/DatanucleusIssue496/tree/workingCase) 

Commit causing behaviour change between datanucleus 5.x and 6.x: https://github.com/datanucleus/datanucleus-rdbms/commit/b99df3c803862f9e9feacc7891461bcb21160b38

For reference attaching the stacktrace:
```
NestedThrowablesStackTrace:
Table "`PERSON`" has been specified with a primary-key to include column "`PRODUCT_NAME`" but this column is not found in the table. Please check your <primary-key> column specification.
org.datanucleus.exceptions.NucleusUserException: Table "`PERSON`" has been specified with a primary-key to include column "`PRODUCT_NAME`" but this column is not found in the table. Please check your <primary-key> column specification.
	at org.datanucleus.store.rdbms.table.ElementContainerTable.applyUserPrimaryKeySpecification(ElementContainerTable.java:224)
	at org.datanucleus.store.rdbms.table.CollectionTable.initialize(CollectionTable.java:236)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.initializeClassTables(RDBMSStoreManager.java:3449)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.run(RDBMSStoreManager.java:3072)
	at org.datanucleus.store.rdbms.AbstractSchemaTransaction.execute(AbstractSchemaTransaction.java:118)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.manageClasses(RDBMSStoreManager.java:1666)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.getDatastoreClass(RDBMSStoreManager.java:670)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.getDatastoreClass(RDBMSPersistenceHandler.java:110)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:196)
	at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4614)
	at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:4591)
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2076)
	at org.datanucleus.ExecutionContext.persistObjectInternal(ExecutionContext.java:320)
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1924)
	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1785)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:697)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:722)
	at com.github.raghav.Main.main(Main.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by Aggarwal-Raghav** [comment] 2024-08-20 14:20
@andyjefferson, can you please provide your insights on this?

**Comment by andyjefferson** [comment] 2024-08-20 16:06
Can't reproduce any problem. I put your "test" into the standard template format (as the docs request), and put it here 
https://github.com/andyjefferson/rdbms-496/tree/master

I also removed the makePersistent of the Person objects (which are embedded-only, so should not be persisted in their own right anyway). I saw no issue with any schema handling. Using Linux, and MariaDB. All is saved in UPPERCASE

CREATE TABLE PRODUCT
(
    PRODUCT_ID BIGINT NOT NULL AUTO_INCREMENT,
    PRODUCT_DESCRIPTION VARCHAR(767) BINARY NULL,
    PRODUCT_NAME VARCHAR(128) BINARY NULL,
    CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID)
) ENGINE=INNODB

If using Windows, as the docs have always said, you may need to set "datanucleus.identifier.case" as "lowercase". Suggest that you revise what this test shows to match reasonable behaviour. If you want the Person objects persisted into a Person table then remove embedded-only.

**Comment by Aggarwal-Raghav** [comment] 2024-08-20 16:25
@andyjefferson , Thanks for the quick reply and converting project to test template.
The same project  https://github.com/andyjefferson/rdbms-496/tree/master when I try with mysql (https://github.com/andyjefferson/rdbms-496/pull/1), it is throwing the below error

<img width="1512" alt="Screenshot 2024-08-20 at 9 47 21 PM" src="https://github.com/user-attachments/assets/e1f650d3-e2c5-4754-905c-9d132d08c8ea">

**Comment by andyjefferson** [comment] 2024-08-20 16:38
If some column is "not found in the table" then define what IS found in the table. Only you can see your database. Given that those col names have quotes then they need to be UPPER CASE. If you haven't defined them in UPPER CASE (or set that persistence property I mentioned) then change your settings. 

And as said above, Person shouldn't have a table if "embedded-only". So decide what you are using it for.

**Comment by Aggarwal-Raghav** [comment] 2024-08-20 17:15
My bad, made a mistake in package.jdo file. Will correct it and revert back to you.

**Comment by Aggarwal-Raghav** [comment] 2024-08-26 11:15
As per our discussion in the mail, adding the details here for future context:

I have written a new test case similar to hive package.jdo. I have tested this testcase with 5.x (Java8) and it is passing (Attaching the datanucleus logs and mysql tables screenshot) but the same testcase with datanucleus 6.x is failing. Attaching the failure logs for the same.

Project URL: https://github.com/Aggarwal-Raghav/rdbms-496
branch master: For java 17, datanucleus 6.x
branch 5.x: For java8, datanucleus 5.x

When I debugged the failure case I found that the string comparison in applyUserPrimaryKeySpecification is causing this issue because of backticks present in column name. Attaching the debug screenshot also.

[datnucleus_5.x_success.log](https://github.com/user-attachments/files/16747614/datnucleus_5.x_success.log)
[datnucleus_6.x_failure.log](https://github.com/user-attachments/files/16747615/datnucleus_6.x_failure.log)
[hive_err.txt](https://github.com/user-attachments/files/16747644/hive_err.txt)
<img width="590" alt="Mysql_Datanucleus_5 x" src="https://github.com/user-attachments/assets/8f7b7965-4a14-4c87-b28c-a31637371505">
<img width="1512" alt="DEBUG" src="https://github.com/user-attachments/assets/36e55733-d3ef-4b68-a26b-0fe2add576b9">

**Comment by Aggarwal-Raghav** [comment] 2024-08-26 11:17
Thanks @andyjefferson , for the quick fix. For me the fix is working. The UT also passed and Apache Hive HMS is also starting. I will check with Hive community also to verify the fix. 

Is there any plan to release 6.0.8 anytime soon?

**Comment by andyjefferson** [comment] 2024-08-26 11:43
Marking as fixed. Aim to release 6.0.8 in the next few days

**Closed by andyjefferson** 2024-08-26 11:43 UTC
Labels: bug

**Comment by andyjefferson** [comment] 2024-08-27 04:38
FYI, 6.0.8 released

**Comment by Aggarwal-Raghav** [comment] 2024-08-27 04:49
Thanks @andyjefferson
