### ISSUE TITLE
ResultClassROF can fail to set fields/properties when JDBC driver returns unassignable type

### ISSUE THREAD

**Issue by aley2003** [datanucleus/datanucleus-rdbms#457] opened 2023-01-11 10:08 UTC
Actually ResultClassROF.getResultObject() uses a getter specific to the resultClass (if resultClass is a simple class).
In all other cases ResultSet.getObject() will be called. 
The Object got from getObject() needs to be converted afterwards to match the result class field.
Unfortunately the conversion works for the first row fetched only. 

I have enhanced ResultClassROF to support ResultSet getters specific to the field classes.
I will try to create a pull request for it.

**Comment by aley2003** [comment] 2023-01-11 10:43
Created pull request https://github.com/datanucleus/datanucleus-rdbms/pull/458

**Comment by andyjefferson** [comment] 2023-01-14 15:49
Please provide a simple testcase that demonstrates the problem. Test suites need to be able to recreate such things.

**Comment by aley2003** [comment] 2023-01-17 09:49
How can I write a test case that shows how Datanucleus fetch data from the database (in this case which ResultSet getter has been called)?

I have problems with the mapping of SQL queries to ResultObjects (with Oracle 11g).
I have seen in debugger, that there was a call of ResultSet.getObject() for all my number columns.
In Oracle ResultSet.getObject() deliveres a BigDecimal for all number types.
This leads to error messages like

`Query needs to return objects of type "..." but it was impossible to set the field "..." type "java.math.BigDecimal". The field should have either a public set/put method, or be public.`

I have to add an setter with a BigDecimal parameter to my result class for all number fields (of type short, int, Integer, Long, ...).

**Comment by aley2003** [comment] 2023-01-17 12:06
Using ResultSet.getInt()/getLong()/... hides a problem with setting the values in the result object fields.
For example the BigDecimal got from Oracle has to be converted to an int. 
This works on the first row of the ResultSet because of the conversion in the catch in ResultClassROF.getObject() line 456 .
For the following rows ResultClassFieldSetter.set will be called directely with the BigDecimal. At this point, there will be no conversion of the BigDecimal to Integer, because Integer is not assignable from BigDecimal (ResultClassROF:889).
This results in the 021204 NucleusUserException in ResultClassROF:343 mentioned above.

**Comment by aley2003** [comment] 2023-01-17 12:21
My test case can reproduce the problem but I was able to reproduce the problem with Oracle only.
Strangely it does get no error with 'mvn clean compile test' but if I call SimpleTestMain directly.

[test-jdo-sql-ResultSetROF-getObject.zip](https://github.com/datanucleus/datanucleus-rdbms/files/10434908/test-jdo-sql-ResultSetROF-getObject.zip)

**Comment by andyjefferson** [comment] 2023-01-18 14:46
Thx. The testcase reproduces a problem using Junit on Oracle (11g) (no need for any "main"), due to how Oracle JDBC maps types

**Comment by andyjefferson** [comment] 2023-01-18 17:05
Suggest that you try with the change made above, since that is way simpler than your PR and works.for.me

**Comment by aley2003** [comment] 2023-01-19 13:06
It looks like your commit solves the conversions problem for Oracle. Thx.

My commit would be an additional enhancement for the way the data is fetched from the ResultSet.
ResultClassROF.getResultObject(ResultSet, int) has an optimization to use the suitable getter (instead of getObject()), if the query has a simple return type. My commit expands this optimization for the fields of the class in case of a class return type.

**Comment by andyjefferson** [comment] 2023-01-20 09:35
Marking as fixed, but retaining PR since would be nice to rework the whole class and could use as part of that

**Closed by andyjefferson** 2023-01-20 09:35 UTC
Labels: bug
